version: '3.6'

services:
  api:
    container_name: api
    image: quay.io/go-skynet/local-ai:latest
    # As initially LocalAI will download the models defined in PRELOAD_MODELS
    # you might need to tweak the healthcheck values here according to your network connection.
    # Here we give a timespan of 20m to download all the required files.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 20
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]
    restart: unless-stopped
    privileged: true
 
networks:
  default:
     name: ai
     external: true
